/*
 * DO NOT EDIT -- generated by the Makefile
 */

#if !defined(__LONGLONG_H__)
#define __LONGLONG_H__

/* do we have/want to use a long long type? */
#undef HAVE_64BIT_LONG_LONG	/* no */

/*
 * NO64BIT_LONG_LONG undef HAVE_64BIT_LONG_LONG
 */
#if defined(NO64BIT_LONG_LONG)
#undef HAVE_64BIT_LONG_LONG
#endif /* NO64BIT_LONG_LONG */

#endif /* !__LONGLONG_H__ */
